global:
  scrape_interval: 5s
scrape_configs:
  - job_name: order-platform
    static_configs:
      - targets:
          - host.docker.internal:8000   # order-service
          - host.docker.internal:8001   # inventory-service
          - host.docker.internal:8002   # payment-service
          - host.docker.internal:8003   # notification-service
